parameters:
  harmony_modular.router.options:
    cache_dir: "%kernel.cache_dir%/modular"
    debug: "%kernel.debug%"

services:
  harmony_modular.doctrine.modular_subscriber:
    class: Harmony\Bundle\ModularBundle\Doctrine\ModularSubscriber
    arguments:
      - "@service_container"
      - "%harmony_modular.module_class%"
    tags:
      - { name: doctrine.event_subscriber }
  harmony_modular.metadata.factory:
    class: Harmony\Component\ModularRouting\Metadata\MetadataFactory
    arguments:
      - "@harmony_modular.metadata.resource_loader"
      - "@routing.loader"
      - "%harmony_modular.router.resource%"
      - "%harmony_modular.router.resource_type%"
  harmony_modular.metadata.resource_loader:
    class: Symfony\Component\Config\Loader\DelegatingLoader
    arguments:
      - "@harmony_modular.metadata.resource_resolver"
  harmony_modular.metadata.resource_loader.yml:
    class: Harmony\Component\ModularRouting\Metadata\Loader\YamlFileLoader
    arguments:
      - "@file_locator"
    tags:
      - { name: harmony_modular.metadata.resource_loader }
  harmony_modular.metadata.resource_resolver:
    class: Symfony\Component\Config\Loader\LoaderResolver
    public: false
  harmony_modular.module_manager.doctrine:
    class: Harmony\Component\ModularRouting\Doctrine\ModuleManager
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%harmony_modular.module_class%"
    calls:
      - ["setModularIdentifier", ["%harmony_modular.module_identifier%"]]
  harmony_modular.module_manager.static:
    class: Harmony\Component\ModularRouting\Manager\StaticModuleManager
    arguments:
      - "%harmony_modular.module_class%"
  harmony_modular.param_converter.module:
    class: Harmony\Bundle\ModularBundle\Request\ModuleParamConverter
    arguments:
      - "@harmony_modular.module_manager"
    tags:
      - { name: request.param_converter, priority: -1, converter: harmony_module_param_converter }
  harmony_modular.param_converter.modular:
    class: Harmony\Bundle\ModularBundle\Request\ModularParamConverter
    arguments:
      - "@doctrine"
      - "@harmony_modular.module_manager"
    tags:
      - { name: request.param_converter, priority: 1, converter: harmony_modular_param_converter }
  harmony_modular.provider.segment:
    class: Harmony\Component\ModularRouting\Provider\SegmentProvider
    arguments:
      - "@harmony_modular.module_manager"
      - "%harmony_modular.module_identifier%"
  harmony_modular.router:
    class: Harmony\Component\ModularRouting\ModularRouter
    arguments:
      - "@harmony_modular.provider"
      - "@harmony_modular.metadata.factory"
      - "%harmony_modular.router.options%"
      - "@router.request_context"
    calls:
      - ["setConfigCacheFactory", ["@config_cache_factory"]]
      - ["setRoutePrefix", ["%harmony_modular.route_prefix.path%", "%harmony_modular.route_prefix.defaults%", "%harmony_modular.route_prefix.requirements%"]]
  harmony_modular.routing_subscriber:
    class: Harmony\Bundle\ModularBundle\EventListener\RoutingSubscriber
    arguments:
      - "@service_container"
    tags:
      - { name: kernel.event_subscriber, priority: 100 }
